package automod_legacy

// These words are listed in in alphabethical order.
var BuiltinSwearWords = map[string]bool{
		"anus":        true,
	"arse":        true,
	"ass":         true,
	"b1tch":       true,
	"b1tch":       false,
	"ballsack":    true,
	"bastard":     true,
	"bitch":       true,
	"bitch":       false,
	"biatch":      true,
	"blowjob":     true,
	"bollock":     true,
@@ -28,16 +28,16 @@ var BuiltinSwearWords = map[string]bool{
	"erection":    true,
	"fag":         true,
	"faggot":      true,
	"feck":        true,
	"feck":        false,
	"fellate":     true,
	"fellatio":    true,
	"felching":    true,
	"fuck":        true,
	"fuck":        false,
	"fucks":       true,
	"fudgepacker": true,
	"genitals":    true,
	"hell":        true,
	"jerk":        true,
	"hell":        false,
	"jerk":        false,
	"jizz":        true,
	"knobend":     true,
	"labia":       true,
@@ -52,8 +52,8 @@ var BuiltinSwearWords = map[string]bool{
	"pussy":       true,
	"scrotum":     true,
	"sex":         true,
	"shit":        true,
	"sh1t":        true,
	"shit":        false,
	"sh1t":        false,
	"slut":        true,
	"smegma":      true,
	"spunk":       true,
@@ -69,7 +69,7 @@ var BuiltinSwearWords = map[string]bool{
	"tits":        true,
	"titty":       true,
	"asshole":     true,
	"fvck":        true,
	"fvck":        false,
	"asshat":      true,
	"pu55y":       true,
	"pen1s":       true,
